// SPDX-License-Identifier: AGPL-3.0-only
// Homebrew publishes one JSON document for homebrew/core with every formula's
// bottles. The collector ships a dated snapshot of the names, split by whether
// any bottle is built for Linux, so the tools rung can grey out Mac-only
// formulae without a network call at collection time.
import type { Linux } from "./manifest.js";
import { LINUX_BOTTLES } from "./data/linux-bottles.js";

export interface BottleSnapshot {
  /** YYYY-MM-DD the formula list was fetched. */
  fetched: string;
  source: string;
  /** Core formulae with an `all`, `x86_64_linux` or `arm64_linux` bottle. */
  linux: readonly string[];
  /** Core formulae with bottles for macOS only, or none at all. */
  noLinux: readonly string[];
}

const LINUX_BOTTLE_TAGS = ["all", "x86_64_linux", "arm64_linux"];

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** Splits formulae.brew.sh's formula.json into the two name lists, each sorted. */
export function classifyFormulae(data: unknown): Pick<BottleSnapshot, "linux" | "noLinux"> {
  const linux: string[] = [];
  const noLinux: string[] = [];
  if (!Array.isArray(data)) return { linux, noLinux };
  for (const f of data) {
    if (!isRecord(f) || typeof f["name"] !== "string") continue;
    const bottle = isRecord(f["bottle"]) ? f["bottle"] : undefined;
    const stable = bottle !== undefined && isRecord(bottle["stable"]) ? bottle["stable"] : undefined;
    const files = stable !== undefined && isRecord(stable["files"]) ? stable["files"] : {};
    (LINUX_BOTTLE_TAGS.some(tag => tag in files) ? linux : noLinux).push(f["name"]);
  }
  linux.sort();
  noLinux.sort();
  return { linux, noLinux };
}

const list = (names: readonly string[]): string => names.map(n => `    ${JSON.stringify(n)},\n`).join("");

/** The generated source of src/data/linux-bottles.ts. */
export function renderSnapshot(s: BottleSnapshot): string {
  return [
    "// SPDX-License-Identifier: AGPL-3.0-only",
    "// Generated by scripts/fetch-linux-bottles.mjs; refresh with `pnpm --filter @wsp/collect run bottles`.",
    'import type { BottleSnapshot } from "../brew-bottles.js";',
    "",
    "export const LINUX_BOTTLES: BottleSnapshot = {",
    `  fetched: ${JSON.stringify(s.fetched)},`,
    `  source: ${JSON.stringify(s.source)},`,
    `  linux: [\n${list(s.linux)}  ],`,
    `  noLinux: [\n${list(s.noLinux)}  ],`,
    "};",
    "",
  ].join("\n");
}

const sets = new WeakMap<BottleSnapshot, { linux: Set<string>; noLinux: Set<string> }>();

/** A formula outside homebrew/core (a tap, or one added since the snapshot) is unknown. */
export function linuxSupport(formula: string, snapshot: BottleSnapshot = LINUX_BOTTLES): Linux {
  let s = sets.get(snapshot);
  if (s === undefined) {
    s = { linux: new Set(snapshot.linux), noLinux: new Set(snapshot.noLinux) };
    sets.set(snapshot, s);
  }
  if (s.linux.has(formula)) return "yes";
  if (s.noLinux.has(formula)) return "no";
  return "unknown";
}
