// No @docusaurus/types import: it is not a dependency of core, and this config does
// not earn one.
//
// Docs-only mode: routeBasePath "/" puts the docs at the site root, so there is no
// separate landing page and no second navbar entry pointing at the same content.
// intro.md carries `slug: /` to claim the root itself.
//
// The sidebar is autogenerated from the docs/ tree — folders become categories via
// their _category_.json, order comes from sidebar_position front matter — so there
// is no sidebars.ts either.
export default {
  title: "Tasks",
  url: "http://localhost:3001",
  baseUrl: "/",
  presets: [["classic", { docs: { routeBasePath: "/" }, blog: false }]],
  themeConfig: {
    navbar: {
      title: "Tasks",
      items: [{ href: "http://localhost:3000", label: "Open the app", position: "right" }],
    },
    docs: { sidebar: { hideable: true } },
  },
};
