/** The artifact you show someone: what was tried, what it looked like, what passed. */
import { writeFileSync, mkdirSync } from "node:fs"
import { dirname } from "node:path"
import type { Trace, RunResult } from "./types.js"

const esc = (s: string) =>
  s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!)

export function writeReport(path: string, trace: Trace, run: RunResult | null): void {
  mkdirSync(dirname(path), { recursive: true })
  // Order matters: an unfinished exploration outranks a green run, because a spec
  // that passes while covering only the first third of the flow is the most
  // misleading thing this report could show.
  const ok = run && run.failed === 0
  const verdict = trace.failed
    ? ["incomplete · flow never finished", "#d97706"]
    : !run
      ? ["did not run", "#9ca3af"]
      : ok
        ? [`verified · ${run.passed} passing`, "#16a34a"]
        : [`${run.failed} failing`, "#dc2626"]

  writeFileSync(
    path,
    `<!doctype html><meta charset="utf-8"><title>ghostspec — ${esc(trace.goal)}</title>
<style>
 :root{color-scheme:light dark;--bg:#fff;--fg:#111;--dim:#666;--line:#e5e5e5;--card:#fafafa}
 @media(prefers-color-scheme:dark){:root{--bg:#0d0d0d;--fg:#eee;--dim:#999;--line:#262626;--card:#161616}}
 *{box-sizing:border-box}
 body{margin:0;padding:2.5rem 1.5rem;background:var(--bg);color:var(--fg);
      font:15px/1.6 ui-sans-serif,system-ui,sans-serif;max-width:56rem;margin-inline:auto}
 h1{font-size:1.5rem;margin:0 0 .25rem}
 .goal{color:var(--dim);margin-bottom:1.5rem}
 .badge{display:inline-block;padding:.15rem .6rem;border-radius:999px;color:#fff;font-size:.8rem;font-weight:600}
 ol{padding-left:1.2rem} li{margin:.6rem 0}
 code{background:var(--card);padding:.1rem .35rem;border-radius:4px;
      font:13px ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-all}
 .note{color:var(--dim);font-size:.88rem}
 pre{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:1rem;
     overflow-x:auto;font:13px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}
 img{width:100%;border:1px solid var(--line);border-radius:8px;margin:.5rem 0}
 a{color:inherit} hr{border:0;border-top:1px solid var(--line);margin:2rem 0}
</style>
<h1>${esc(trace.goal)}</h1>
<div class="goal"><a href="${esc(trace.url)}">${esc(trace.url)}</a> ·
  <span class="badge" style="background:${verdict[1]}">${esc(String(verdict[0]))}</span></div>
${trace.failed ? `<p><strong>Exploration stopped:</strong> ${esc(trace.failed)}</p>` : ""}
${
  trace.replayUrl
    ? `<p class="note">Session replay (rrweb NDJSON, plays in any rrweb player):
         <a href="${esc(trace.replayUrl)}">${esc(trace.replayUrl)}</a>${
           trace.replayUrl.startsWith("http")
             ? " — presigned link, expires ~15 min after the run"
             : ""
         }</p>`
    : ""
}

<h2>What it did</h2>
<ol>${trace.steps
  .map(
    (s) =>
      `<li><code>${esc(s.action)}${s.locator ? ` ${esc(s.locator)}` : ""}${
        s.value ? ` → ${esc(s.value)}` : ""
      }</code><br><span class="note">${esc(s.note)}</span></li>`,
  )
  .join("")}</ol>

${trace.screenshots.length ? `<h2>Screens</h2>${trace.screenshots.map((s) => `<img src="${esc(s)}" alt="">`).join("")}` : ""}

${run ? `<hr><h2>Generated spec</h2><pre>${esc(run.spec)}</pre>
<h2>Run output</h2><pre>${esc(run.output)}</pre>` : ""}
<hr><p class="note">Generated by <a href="https://github.com/badnikhil/ghostspec">ghostspec</a>,
on a <a href="https://getsolari.com">Solari</a> cloud browser.</p>`,
  )
}
